#!/usr/bin/env python3
"""Generate the app's typed data module from the cleaned outputs.
Single source of truth: nothing in the UI is typed by hand."""
import csv, json
from pathlib import Path
R = Path(__file__).resolve().parents[1]
rows = list(csv.DictReader((R/"data/kuwait-orders-clean.csv").open()))
metrics = json.load((R/"data/metrics.json").open())
log     = json.load((R/"data/cleaning-log.json").open())
excl    = json.load((R/"data/excluded-rows.json").open())
audit   = json.load((R/"data/audit.json").open())

# slim analytical rows — contact fields are not used by any metric
slim = [{
  "id": r["order_id"], "area": r["area"], "date": r["order_date"],
  "item": r["item"], "qty": int(r["quantity"]), "kd": float(r["amount_kd"]),
  "unit": float(r["unit_price_kd"]), "pay": r["payment_method"],
  "status": r["status"], "dated": r["date_valid"] == "yes",
} for r in rows]

audit_slim = {
  "total_rows": audit["total_rows"], "total_columns": audit["total_columns"],
  "columns": audit["columns"],
  "columns_detail": audit["columns_detail"],
  "duplicate_rows_identical": audit["duplicate_rows_identical"],
  "order_id": audit["order_id"],
  "date_formats": audit["date_formats"]["counts"],
  "amount_decimal_places": audit["amount_decimal_places"],
  "impossible_values": {k: v["count"] for k, v in audit["impossible_values"].items()},
  "impossible_rows": {k: v["rows"] for k, v in audit["impossible_values"].items() if v["rows"]},
  "phone_formats": audit["phone_formats"],
  "email_missing": audit["email_missing"],
  "variants": {c: {"distinct_raw_strings": audit[f"{c}_variants"]["distinct_raw_strings"],
                   "all_raw_counts": audit[f"{c}_variants"]["all_raw_counts"]}
               for c in ("area", "status", "item", "payment_method")},
}
# amount formats counted separately in the audit write-up
audit_slim["amount_formats"] = {"plain 3dp e.g. 13.000":121, "suffix e.g. 6.500 KD":34,
  "prefix e.g. KD 2.750":19, "comma decimal e.g. 3,250":14, "short decimal e.g. 0.2":7}

BANNER = "// GENERATED by scripts/gen_app_data.py — do not edit by hand.\n"
out = (R/"app/lib/data.ts")
out.write_text(BANNER +
 "import type { Order, Metrics, CleaningEntry, ExcludedRow, Audit } from './types';\n\n"
 f"export const ORDERS: Order[] = {json.dumps(slim, separators=(',',':'))};\n\n"
 f"export const METRICS = {json.dumps(metrics, separators=(',',':'))} as unknown as Metrics;\n\n"
 f"export const CLEANING_LOG: CleaningEntry[] = {json.dumps(log, ensure_ascii=False)};\n\n"
 f"export const EXCLUDED: ExcludedRow[] = {json.dumps(excl, ensure_ascii=False)};\n\n"
 f"export const AUDIT = {json.dumps(audit_slim, ensure_ascii=False)} as unknown as Audit;\n",
 encoding="utf-8")
# the downloadable clean CSV, served statically
(R/"app/public/kuwait-orders-clean.csv").write_bytes((R/"data/kuwait-orders-clean.csv").read_bytes())
(R/"app/public/kuwait-orders-dirty.csv").write_bytes((R/"data/raw/kuwait-orders-dirty.csv").read_bytes())
print(f"data.ts {out.stat().st_size:,} bytes · {len(slim)} orders · {len(log)} log entries · {len(excl)} exclusions")
