#!/usr/bin/env python3
"""Generate the app's typed data module from the cleaned outputs.
Single source of truth: nothing in the UI is typed by hand."""
import csv, json
from pathlib import Path
R = Path(__file__).resolve().parents[1]
rows = list(csv.DictReader((R/"data/kuwait-orders-clean.csv").open()))
metrics = json.load((R/"data/metrics.json").open())
log     = json.load((R/"data/cleaning-log.json").open())
excl    = json.load((R/"data/excluded-rows.json").open())
audit   = json.load((R/"data/audit.json").open())

# slim analytical rows — contact fields are not used by any metric
slim = [{
  "id": r["order_id"], "area": r["area"], "date": r["order_date"],
  "item": r["item"], "qty": int(r["quantity"]), "kd": float(r["amount_kd"]),
  "unit": float(r["unit_price_kd"]), "pay": r["payment_method"],
  "status": r["status"], "dated": r["date_valid"] == "yes",
} for r in rows]

audit_slim = {
  "total_rows": audit["total_rows"], "total_columns": audit["total_columns"],
  "columns": audit["columns"],
  "columns_detail": {"area": audit["columns_detail"]["area"]},
  "duplicate_rows_identical": audit["duplicate_rows_identical"],
  "order_id": {k: audit["order_id"][k] for k in ("distinct","ids_appearing_more_than_once","extra_rows_beyond_first")},
  "date_formats": audit["date_formats"]["counts"],
  "amount_decimal_places": audit["amount_decimal_places"],
  "impossible_values": {k: v["count"] for k, v in audit["impossible_values"].items()},
  "phone_formats": audit["phone_formats"],
  "email_missing": audit["email_missing"],
  # only the counts the Quality tab actually renders — the full raw-value tables
  # stay in data/audit.json rather than shipping to every visitor
  "variants": {c: {"distinct_raw_strings": audit[f"{c}_variants"]["distinct_raw_strings"]}
               for c in ("area", "status", "item", "payment_method")},
}
# amount formats counted separately in the audit write-up
audit_slim["amount_formats"] = {"plain 3dp e.g. 13.000":121, "suffix e.g. 6.500 KD":34,
  "prefix e.g. KD 2.750":19, "comma decimal e.g. 3,250":14, "short decimal e.g. 0.2":7}

# 189 rows as verbose JSON is ~35 KB of repeated key names. Encoding them as one
# delimited line each, with the repeated strings in lookup tables, cuts that to a
# few KB and costs one tiny decoder that runs once at module load.
AREAS = sorted({r["area"] for r in slim})
ITEMS = sorted({r["item"] for r in slim})
PAYS  = sorted({r["pay"]  for r in slim})
STATS = ["Delivered", "Pending", "Cancelled"]
DATES = sorted({r["date"] for r in slim if r["date"]})
def enc(r):
    return "|".join([
        r["id"].replace("KW-", ""), str(AREAS.index(r["area"])), str(ITEMS.index(r["item"])),
        str(DATES.index(r["date"])) if r["date"] else "",
        str(r["qty"]), f'{r["kd"]:g}', f'{r["unit"]:g}',
        str(PAYS.index(r["pay"])), str(STATS.index(r["status"])),
    ])
PACKED = "\n".join(enc(r) for r in slim)

BANNER = "// GENERATED by scripts/gen_app_data.py — do not edit by hand.\n"
out = (R/"app/lib/data.ts")
out.write_text(BANNER +
 "import type { Order, Metrics, CleaningEntry, ExcludedRow, Audit } from './types';\n\n"
 f"const A = {json.dumps(AREAS)};\n"
 f"const I = {json.dumps(ITEMS)};\n"
 f"const P = {json.dumps(PAYS)};\n"
 f"const S = {json.dumps(STATS)} as const;\n"
 f"const D = {json.dumps(DATES)};\n\n"
 "const PACKED = `" + PACKED + "`;\n\n"
 "export const ORDERS: Order[] = PACKED.split('\\n').map((line) => {\n"
 "  const [id, a, i, d, q, kd, unit, p, s] = line.split('|');\n"
 "  return { id: 'KW-' + id, area: A[+a], item: I[+i], date: d === '' ? '' : D[+d],\n"
 "           dated: d !== '', qty: +q, kd: +kd, unit: +unit, pay: P[+p],\n"
 "           status: S[+s] as Order['status'] };\n"
 "});\n\n"
 f"export const METRICS = {json.dumps(metrics, separators=(',',':'))} as unknown as Metrics;\n\n"
 f"export const CLEANING_LOG: CleaningEntry[] = {json.dumps(log, ensure_ascii=False)};\n\n"
 f"export const EXCLUDED: ExcludedRow[] = {json.dumps(excl, ensure_ascii=False)};\n\n"
 f"export const AUDIT = {json.dumps(audit_slim, ensure_ascii=False)} as unknown as Audit;\n",
 encoding="utf-8")
print(f"data.ts {out.stat().st_size:,} bytes · {len(slim)} orders · {len(log)} log entries · {len(excl)} exclusions")
